server.port=${PORT:8080}
app.group-name=${GROUP_NAME:Grupo 8}
app.database.name=${DB_NAME:aula-db}
app.database.port=${DB_PORT:3306}
app.database.user=${DB_USER:root}
app.database.password=${DB_PASSWORD:}
app.database.primary-host=${DB_PRIMARY_HOST:localhost}
app.database.replica-hosts=${DB_REPLICA_HOSTS:localhost}
app.database.use-ssl=${DB_USE_SSL:false}
app.generator.enabled=${GENERATOR_ENABLED:true}
app.generator.interval-ms=${GENERATOR_INTERVAL_MS:5000}
spring.main.banner-mode=off
